undercloud_memory: 8000

control_memory: 6000
compute_memory: 2000

overcloud_nodes:
  - name: control_0
    flavor: control
  - name: compute_0
    flavor: compute

networks:
  - name: external
    bridge: brext
    address: 192.168.23.1
    netmask: 255.255.255.0

  - name: overcloud
    bridge: brovc
